---
- name: Update web servers
  hosts: webservers
  remote_user: ec2-user

  tasks:
    - name: Install git
      ansible.builtin.yum:
        name: git
        state: latest
      become: yes
    - name: Install Python
      ansible.builtin.yum:
        name: python
        state: 3.7
      become: yes
    - name: Install poetry
      ansible.builtin.shell:
        cmd: curl -sSL https://install.python-poetry.org | python3 -
        creates: ~/.local/bin/poetry
    - name: Create app directory
      ansible.builtin.file:
        path: /opt/todoapp
        state: directory
        mode: '0755'
        owner: ec2-user
      become: yes
    - name: Clone todo_app at main
      ansible.builtin.git:
        repo: https://github.com/achamberlain999/DevOps-Course-Starter.git
        dest: /opt/todoapp
        depth: 1
    - name: Install app dependencies
      ansible.builtin.command:
        cmd: ~/.local/bin/poetry install
        chdir: /opt/todoapp