name: Continuous Integration
on:
  push:
    paths-ignore:
    - docs
    - '**.md'
  pull_request:
    paths-ignore:
      - docs
      - '**.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build --target test --tag todo-app:test .
    - run: docker run --name tasko-test todo-app:test

  docker-build:
    name: Build production docker image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v3

      - run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref }}

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build --platform linux/amd64 --target production --tag alechasoftwire/todo-app:prod .
      
      - run: docker push alechasoftwire/todo-app:prod