name: Continuous Integration
on:
  push:
    paths-ignore:
    - docs
    - '**.md'
  pull_request:
    paths-ignore:
      - docs
      - '**.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build --target test --tag todo-app:test .
    - run: docker run --name tasko-test todo-app:test

  docker-build-and-deploy:
    name: Build & deploy production docker image
    needs: test
    # if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: actions/checkout@v3

      - name: Build docker image
        run: docker build --platform linux/amd64 --target production --tag alechasoftwire/todo-app:prod .

      - name: Deploy to Docker Hub
        run: docker push alechasoftwire/todo-app:prod

  restart-app:
    name: Restart Azure app
    needs: docker-build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Azure restart
        run: curl -dH -X POST '${{ secrets.AZURE_WEBHOOK }}' --fail